In [1]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout
from keras.preprocessing.image import ImageDataGenerator
import os

C:\Users\bharg\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
classifier = Sequential()

In [3]:
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))

In [4]:
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [5]:
classifier.add(Flatten())

In [6]:
classifier.add(Dense(units = 128, activation = 'relu'))

In [7]:
classifier.add(Dropout(0.5))

In [8]:
classifier.add(Dense(units = 10, activation = 'softmax'))

In [9]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [10]:
train_datagen = ImageDataGenerator(rescale = 1./255,
shear_range = 0.2,
zoom_range = 0.2,
horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)
training_set = train_datagen.flow_from_directory('train',
target_size = (64, 64),
batch_size = 30,
class_mode = 'categorical')
# test_set = test_datagen.flow_from_directory('test',
# target_size = (64, 64),
# batch_size = 1,
# class_mode = 'categorical')


Found 22424 images belonging to 10 classes.


In [11]:
STEP_SIZE_TRAIN=training_set.n/30
# STEP_SIZE_VALID=test_set.n
classifier.fit_generator(training_set,
# steps_per_epoch = 100,
epochs = 3,
steps_per_epoch=STEP_SIZE_TRAIN,
# validation_data=test_set,
# validation_steps=STEP_SIZE_VALID,
# validation_data = test_set,
# validation_steps = 2000
)

Epoch 1/3
748/747 [==============================] - 360s 481ms/step - loss: 2.1746 - acc: 0.1723
Epoch 2/3
748/747 [==============================] - 349s 467ms/step - loss: 1.7082 - acc: 0.3471
Epoch 3/3
748/747 [==============================] - 351s 469ms/step - loss: 1.4120 - acc: 0.4643


In [14]:
import numpy as np
from keras.preprocessing import image

test_path = 'test/test_images'
for img in os.listdir(test_path):
    input_path = os.path.join(test_path, img)
    test_image = image.load_img(input_path, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = classifier.predict(test_image)
    training_set.class_indices
#     print(training_set.class_indices)
    print(result)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.3476978e-36 0.0000000e+00 1.0000000e+00 0.0000000e+00 7.0554055e-27]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[9.9384555e-26 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0.

[[9.60047e-19 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.30798206 0.         0.         0.         0.6920179  0.
  0.         0.         0.         0.        ]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 0.0000000e+00 7.8605900e-10 2.4607268e-20
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[[1.3256977e-33 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[1.8738975e-09 0.0000000e+00 0.